### ISSUE TITLE
Version 1.0.3 not Tags correctly for go modules

### ISSUE THREAD

**Issue by jcheyer** [thanhpk/randstr#3]
GO111MODULE=on go build 
produces

main.go:10:2: import "github.com/thanhpk/randstr" is a program, not an importable package

This happens because your 1.0.3 Tag is mission the prepending 'v'

That's the reason why go in module mode is using v1.0.2 which has a.go inside which is package main.

Could you please fix the Tag ?

**Comment by thanhpk** [comment]
sure, I have just pushed v1.0.4 tag
